spring.application.name=api-agroconecta

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}?prepareThreshold=0
spring.datasource.username=${DATABASE_USERNAME}
#este es un comentario
spring.datasource.password=${DATABASE_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#AgroconectaT8
jwt.secret=3e7b6efdd1b562cfa17034efe4077607c6df3c06914905616791349d6001e6f3
jwt.expiration=86400000

gcp.bucket.name=${GCP_BUCKET_NAME}
spring.cloud.gcp.credentials.location=${GCP_CREDENTIALS_BASE64}

